namespace Sunisoft.IrisSkin
{
    using System;
    using System.Drawing;
    using System.Runtime.InteropServices;

    internal class x40255b11ef821fa3
    {
        public const byte AC_SRC_ALPHA = 1;
        public const byte AC_SRC_OVER = 0;
        public const uint AW_ACTIVATE = 0x20000;
        public const uint AW_BLEND = 0x80000;
        public const uint AW_CENTER = 0x10;
        public const uint AW_HIDE = 0x10000;
        public const uint AW_HOR_NEGATIVE = 2;
        public const uint AW_HOR_POSITIVE = 1;
        public const uint AW_SLIDE = 0x40000;
        public const uint AW_VER_NEGATIVE = 8;
        public const uint AW_VER_POSITIVE = 4;
        public const uint BM_CLICK = 0xf5;
        public const uint BM_GETCHECK = 240;
        public const uint BM_GETIMAGE = 0xf6;
        public const uint BM_GETSTATE = 0xf2;
        public const uint BM_SETCHECK = 0xf1;
        public const uint BM_SETIMAGE = 0xf7;
        public const uint BM_SETSTATE = 0xf3;
        public const uint BM_SETSTYLE = 0xf4;
        public const uint BN_CLICKED = 0;
        public const uint BN_DBLCLK = 5;
        public const uint BN_DISABLE = 4;
        public const uint BN_DOUBLECLICKED = 5;
        public const uint BN_HILITE = 2;
        public const uint BN_KILLFOCUS = 7;
        public const uint BN_PAINT = 1;
        public const uint BN_PUSHED = 2;
        public const uint BN_SETFOCUS = 6;
        public const uint BN_UNHILITE = 3;
        public const uint BN_UNPUSHED = 3;
        public const uint BS_3STATE = 5;
        public const uint BS_AUTO3STATE = 6;
        public const uint BS_AUTOCHECKBOX = 3;
        public const uint BS_AUTORADIOBUTTON = 9;
        public const uint BS_BITMAP = 0x80;
        public const uint BS_BOTTOM = 0x800;
        public const uint BS_CENTER = 0x300;
        public const uint BS_CHECKBOX = 2;
        public const uint BS_DEFPUSHBUTTON = 1;
        public const uint BS_FLAT = 0x8000;
        public const uint BS_GROUPBOX = 7;
        public const uint BS_ICON = 0x40;
        public const uint BS_LEFT = 0x100;
        public const uint BS_LEFTTEXT = 0x20;
        public const uint BS_MULTILINE = 0x2000;
        public const uint BS_NOTIFY = 0x4000;
        public const uint BS_OWNERDRAW = 11;
        public const uint BS_PUSHBOX = 10;
        public const uint BS_PUSHBUTTON = 0;
        public const uint BS_PUSHLIKE = 0x1000;
        public const uint BS_RADIOBUTTON = 4;
        public const uint BS_RIGHT = 0x200;
        public const uint BS_RIGHTBUTTON = 0x20;
        public const uint BS_TEXT = 0;
        public const uint BS_TOP = 0x400;
        public const uint BS_TYPEMASK = 15;
        public const uint BS_USERBUTTON = 8;
        public const uint BS_VCENTER = 0xc00;
        public const uint BST_CHECKED = 1;
        public const uint BST_FOCUS = 8;
        public const uint BST_INDETERMINATE = 2;
        public const uint BST_PUSHED = 4;
        public const uint BST_UNCHECKED = 0;
        public const int CCHILDREN_SCROLLBAR = 5;
        public const uint CS_BYTEALIGNCLIENT = 0x1000;
        public const uint CS_BYTEALIGNWINDOW = 0x2000;
        public const uint CS_CLASSDC = 0x40;
        public const uint CS_DBLCLKS = 8;
        public const uint CS_DROPSHADOW = 0x20000;
        public const uint CS_GLOBALCLASS = 0x4000;
        public const uint CS_HREDRAW = 2;
        public const uint CS_IME = 0x10000;
        public const uint CS_NOCLOSE = 0x200;
        public const uint CS_OWNDC = 0x20;
        public const uint CS_PARENTDC = 0x80;
        public const uint CS_SAVEBITS = 0x800;
        public const uint CS_VREDRAW = 1;
        public const uint DI_COMPAT = 4;
        public const uint DI_DEFAULTSIZE = 8;
        public const uint DI_IMAGE = 2;
        public const uint DI_MASK = 1;
        public const uint DI_NOMIRROR = 0x10;
        public const uint DI_NORMAL = 3;
        public const uint DLGC_BUTTON = 0x2000;
        public const uint DLGC_DEFPUSHBUTTON = 0x10;
        public const uint DLGC_HASSETSEL = 8;
        public const uint DLGC_RADIOBUTTON = 0x40;
        public const uint DLGC_STATIC = 0x100;
        public const uint DLGC_UNDEFPUSHBUTTON = 0x20;
        public const uint DLGC_WANTALLKEYS = 4;
        public const uint DLGC_WANTARROWS = 1;
        public const uint DLGC_WANTCHARS = 0x80;
        public const uint DLGC_WANTMESSAGE = 4;
        public const uint DLGC_WANTTAB = 2;
        public const uint FE_FONTSMOOTHINGCLEARTYPE = 2;
        public const uint FE_FONTSMOOTHINGDOCKING = 0x8000;
        public const uint FE_FONTSMOOTHINGORIENTATIONBGR = 0;
        public const uint FE_FONTSMOOTHINGORIENTATIONRGB = 1;
        public const uint FE_FONTSMOOTHINGSTANDARD = 1;
        public const int GCL_CBCLSEXTRA = -20;
        public const int GCL_CBWNDEXTRA = -18;
        public const int GCL_HBRBACKGROUND = -10;
        public const int GCL_HCURSOR = -12;
        public const int GCL_HICON = -14;
        public const int GCL_HICONSM = -34;
        public const int GCL_HMODULE = -16;
        public const int GCL_MENUNAME = -8;
        public const int GCL_STYLE = -26;
        public const int GCL_WNDPROC = -24;
        public const int GCW_ATOM = -32;
        public const uint GW_CHILD = 5;
        public const uint GW_ENABLEDPOPUP = 6;
        public const uint GW_HWNDFIRST = 0;
        public const uint GW_HWNDLAST = 1;
        public const uint GW_HWNDNEXT = 2;
        public const uint GW_HWNDPREV = 3;
        public const uint GW_MAX = 6;
        public const uint GW_OWNER = 4;
        public const int GWL_EXSTYLE = -20;
        public const int GWL_HINSTANCE = -6;
        public const int GWL_HWNDPARENT = -8;
        public const int GWL_ID = -12;
        public const int GWL_STYLE = -16;
        public const int GWL_USERDATA = -21;
        public const int GWL_WNDPROC = -4;
        public const int HC_ACTION = 0;
        public const int HC_GETNEXT = 1;
        public const int HC_NOREM = 3;
        public const int HC_NOREMOVE = 3;
        public const int HC_SKIP = 2;
        public const int HC_SYSMODALOFF = 5;
        public const int HC_SYSMODALON = 4;
        public const int HCBT_ACTIVATE = 5;
        public const int HCBT_CLICKSKIPPED = 6;
        public const int HCBT_CREATEWND = 3;
        public const int HCBT_DESTROYWND = 4;
        public const int HCBT_KEYSKIPPED = 7;
        public const int HCBT_MINMAX = 1;
        public const int HCBT_MOVESIZE = 0;
        public const int HCBT_QS = 2;
        public const int HCBT_SETFOCUS = 9;
        public const int HCBT_SYSCOMMAND = 8;
        public const int HTBORDER = 0x12;
        public const int HTBOTTOM = 15;
        public const int HTBOTTOMLEFT = 0x10;
        public const int HTBOTTOMRIGHT = 0x11;
        public const int HTCAPTION = 2;
        public const int HTCLIENT = 1;
        public const int HTCLOSE = 20;
        public const int HTERROR = -2;
        public const int HTGROWBOX = 4;
        public const int HTHELP = 0x15;
        public const int HTHSCROLL = 6;
        public const int HTLEFT = 10;
        public const int HTMAINMENU = 0x16;
        public const int HTMAXBUTTON = 9;
        public const int HTMENU = 5;
        public const int HTMINBUTTON = 8;
        public const int HTNOWHERE = 0;
        public const int HTOBJECT = 0x13;
        public const int HTREDUCE = 8;
        public const int HTRIGHT = 11;
        public const int HTSIZE = 4;
        public const int HTSIZEFIRST = 10;
        public const int HTSIZELAST = 0x11;
        public const int HTSYSMENU = 3;
        public const int HTTOP = 12;
        public const int HTTOPLEFT = 13;
        public const int HTTOPRIGHT = 14;
        public const int HTTRANSPARENT = -1;
        public const int HTUSER = 0x100;
        public const int HTVSCROLL = 7;
        public const int HTZOOM = 9;
        public const int HWND_BOTTOM = 1;
        public const int HWND_NOTOPMOST = -2;
        public const int HWND_TOP = 0;
        public const int HWND_TOPMOST = -1;
        public const uint IDC_APPSTARTING = 0x7f8a;
        public const uint IDC_ARROW = 0x7f00;
        public const uint IDC_CROSS = 0x7f03;
        public const uint IDC_HAND = 0x7f89;
        public const uint IDC_HELP = 0x7f8b;
        public const uint IDC_IBEAM = 0x7f01;
        public const uint IDC_ICON = 0x7f81;
        public const uint IDC_NO = 0x7f88;
        public const uint IDC_SIZE = 0x7f80;
        public const uint IDC_SIZEALL = 0x7f86;
        public const uint IDC_SIZENESW = 0x7f83;
        public const uint IDC_SIZENS = 0x7f85;
        public const uint IDC_SIZENWSE = 0x7f82;
        public const uint IDC_SIZEWE = 0x7f84;
        public const uint IDC_UPARROW = 0x7f04;
        public const uint IDC_WAIT = 0x7f02;
        public const int MA_ACTIVATE = 1;
        public const int MA_ACTIVATEANDEAT = 2;
        public const int MA_NOACTIVATE = 3;
        public const int MA_NOACTIVATEANDEAT = 4;
        public const uint MB_ABORTRETRYIGNORE = 2;
        public const uint MB_APPLMODAL = 0;
        public const uint MB_CANCELTRYCONTINUE = 6;
        public const uint MB_DEFAULT_DESKTOP_ONLY = 0x20000;
        public const uint MB_DEFBUTTON1 = 0;
        public const uint MB_DEFBUTTON2 = 0x100;
        public const uint MB_DEFBUTTON3 = 0x200;
        public const uint MB_DEFBUTTON4 = 0x300;
        public const uint MB_DEFMASK = 0xf00;
        public const uint MB_HELP = 0x4000;
        public const uint MB_ICONASTERISK = 0x40;
        public const uint MB_ICONERROR = 0x10;
        public const uint MB_ICONEXCLAMATION = 0x30;
        public const uint MB_ICONHAND = 0x10;
        public const uint MB_ICONINFORMATION = 0x40;
        public const uint MB_ICONMASK = 240;
        public const uint MB_ICONQUESTION = 0x20;
        public const uint MB_ICONSTOP = 0x10;
        public const uint MB_ICONWARNING = 0x30;
        public const uint MB_MISCMASK = 0xc000;
        public const uint MB_MODEMASK = 0x3000;
        public const uint MB_NOFOCUS = 0x8000;
        public const uint MB_OK = 0;
        public const uint MB_OKCANCEL = 1;
        public const uint MB_RETRYCANCEL = 5;
        public const uint MB_RIGHT = 0x80000;
        public const uint MB_RTLREADING = 0x100000;
        public const uint MB_SERVICE_NOTIFICATION = 0x200000;
        public const uint MB_SERVICE_NOTIFICATION_NT3X = 0x40000;
        public const uint MB_SETFOREGROUND = 0x10000;
        public const uint MB_SYSTEMMODAL = 0x1000;
        public const uint MB_TASKMODAL = 0x2000;
        public const uint MB_TOPMOST = 0x40000;
        public const uint MB_TYPEMASK = 15;
        public const uint MB_USERICON = 0x80;
        public const uint MB_YESNO = 4;
        public const uint MB_YESNOCANCEL = 3;
        public const int MF_APPEND = 0x100;
        public const int MF_BITMAP = 4;
        public const int MF_BYCOMMAND = 0;
        public const int MF_BYPOSITION = 0x400;
        public const int MF_CHANGE = 0x80;
        public const int MF_CHECKED = 8;
        public const int MF_DEFAULT = 0x1000;
        public const int MF_DELETE = 0x200;
        public const int MF_DISABLED = 2;
        public const int MF_ENABLED = 0;
        public const int MF_END = 0x80;
        public const int MF_GRAYED = 1;
        public const int MF_HELP = 0x4000;
        public const int MF_HILITE = 0x80;
        public const int MF_INSERT = 0;
        public const int MF_MENUBARBREAK = 0x20;
        public const int MF_MENUBREAK = 0x40;
        public const int MF_MOUSESELECT = 0x8000;
        public const int MF_OWNERDRAW = 0x100;
        public const int MF_POPUP = 0x10;
        public const int MF_REMOVE = 0x1000;
        public const int MF_RIGHTJUSTIFY = 0x4000;
        public const int MF_SEPARATOR = 0x800;
        public const int MF_STRING = 0;
        public const int MF_SYSMENU = 0x2000;
        public const int MF_UNCHECKED = 0;
        public const int MF_UNHILITE = 0;
        public const int MF_USECHECKBITMAPS = 0x200;
        public const uint MN_GETHMENU = 0x1e1;
        public const uint OBJID_ALERT = 0xfffffff6;
        public const uint OBJID_CARET = 0xfffffff8;
        public const uint OBJID_CLIENT = 0xfffffffc;
        public const uint OBJID_CURSOR = 0xfffffff7;
        public const uint OBJID_HSCROLL = 0xfffffffa;
        public const uint OBJID_MENU = 0xfffffffd;
        public const uint OBJID_NATIVEOM = 0xfffffff0;
        public const uint OBJID_QUERYCLASSNAMEIDX = 0xfffffff4;
        public const uint OBJID_SIZEGRIP = 0xfffffff9;
        public const uint OBJID_SOUND = 0xfffffff5;
        public const uint OBJID_SYSMENU = uint.MaxValue;
        public const uint OBJID_TITLEBAR = 0xfffffffe;
        public const uint OBJID_VSCROLL = 0xfffffffb;
        public const uint OBJID_WINDOW = 0;
        public const uint PM_NOREMOVE = 0;
        public const uint PM_NOYIELD = 2;
        public const uint PM_REMOVE = 1;
        public const uint SB_BOTH = 3;
        public const uint SB_BOTTOM = 7;
        public const uint SB_CTL = 2;
        public const uint SB_ENDSCROLL = 8;
        public const uint SB_HORZ = 0;
        public const uint SB_LEFT = 6;
        public const uint SB_LINEDOWN = 1;
        public const uint SB_LINELEFT = 0;
        public const uint SB_LINERIGHT = 1;
        public const uint SB_LINEUP = 0;
        public const uint SB_PAGEDOWN = 3;
        public const uint SB_PAGELEFT = 2;
        public const uint SB_PAGERIGHT = 3;
        public const uint SB_PAGEUP = 2;
        public const uint SB_RIGHT = 7;
        public const uint SB_THUMBPOSITION = 4;
        public const uint SB_THUMBTRACK = 5;
        public const uint SB_TOP = 6;
        public const uint SB_VERT = 1;
        public const uint SBM_ENABLE_ARROWS = 0xe4;
        public const uint SBM_GETPOS = 0xe1;
        public const uint SBM_GETRANGE = 0xe3;
        public const uint SBM_GETSCROLLINFO = 0xea;
        public const uint SBM_SETPOS = 0xe0;
        public const uint SBM_SETRANGE = 0xe2;
        public const uint SBM_SETRANGEREDRAW = 230;
        public const uint SBM_SETSCROLLINFO = 0xe9;
        public const uint SBS_BOTTOMALIGN = 4;
        public const uint SBS_HORZ = 0;
        public const uint SBS_LEFTALIGN = 2;
        public const uint SBS_RIGHTALIGN = 4;
        public const uint SBS_SIZEBOX = 8;
        public const uint SBS_SIZEBOXBOTTOMRIGHTALIGN = 4;
        public const uint SBS_SIZEBOXTOPLEFTALIGN = 2;
        public const uint SBS_SIZEGRIP = 0x10;
        public const uint SBS_TOPALIGN = 2;
        public const uint SBS_VERT = 1;
        public const uint SC_ARRANGE = 0xf110;
        public const uint SC_CLOSE = 0xf060;
        public const uint SC_CONTEXTHELP = 0xf180;
        public const uint SC_DEFAULT = 0xf160;
        public const uint SC_HOTKEY = 0xf150;
        public const uint SC_HSCROLL = 0xf080;
        public const uint SC_KEYMENU = 0xf100;
        public const uint SC_MAXIMIZE = 0xf030;
        public const uint SC_MINIMIZE = 0xf020;
        public const uint SC_MONITORPOWER = 0xf170;
        public const uint SC_MOUSEMENU = 0xf090;
        public const uint SC_MOVE = 0xf010;
        public const uint SC_NEXTWINDOW = 0xf040;
        public const uint SC_PREVWINDOW = 0xf050;
        public const uint SC_RESTORE = 0xf120;
        public const uint SC_SCREENSAVE = 0xf140;
        public const uint SC_SEPARATOR = 0xf00f;
        public const uint SC_SIZE = 0xf000;
        public const uint SC_TASKLIST = 0xf130;
        public const uint SC_VSCROLL = 0xf070;
        public const uint SIF_ALL = 0x1f;
        public const uint SIF_DISABLENOSCROLL = 8;
        public const uint SIF_PAGE = 2;
        public const uint SIF_POS = 4;
        public const uint SIF_RANGE = 1;
        public const uint SIF_TRACKPOS = 0x10;
        public const uint SIZE_MAXHIDE = 4;
        public const uint SIZE_MAXIMIZED = 2;
        public const uint SIZE_MAXSHOW = 3;
        public const uint SIZE_MINIMIZED = 1;
        public const uint SIZE_RESTORED = 0;
        public const uint SPI_GETACCESSTIMEOUT = 60;
        public const uint SPI_GETACTIVEWINDOWTRACKING = 0x1000;
        public const uint SPI_GETACTIVEWNDTRKTIMEOUT = 0x2002;
        public const uint SPI_GETACTIVEWNDTRKZORDER = 0x100c;
        public const uint SPI_GETANIMATION = 0x48;
        public const uint SPI_GETBEEP = 1;
        public const uint SPI_GETBLOCKSENDINPUTRESETS = 0x1026;
        public const uint SPI_GETBORDER = 5;
        public const uint SPI_GETCARETWIDTH = 0x2006;
        public const uint SPI_GETCOMBOBOXANIMATION = 0x1004;
        public const uint SPI_GETCURSORSHADOW = 0x101a;
        public const uint SPI_GETDEFAULTINPUTLANG = 0x59;
        public const uint SPI_GETDESKWALLPAPER = 0x73;
        public const uint SPI_GETDRAGFULLWINDOWS = 0x26;
        public const uint SPI_GETDROPSHADOW = 0x1024;
        public const uint SPI_GETFASTTASKSWITCH = 0x23;
        public const uint SPI_GETFILTERKEYS = 50;
        public const uint SPI_GETFLATMENU = 0x1022;
        public const uint SPI_GETFOCUSBORDERHEIGHT = 0x2010;
        public const uint SPI_GETFOCUSBORDERWIDTH = 0x200e;
        public const uint SPI_GETFONTSMOOTHING = 0x4a;
        public const uint SPI_GETFONTSMOOTHINGCONTRAST = 0x200c;
        public const uint SPI_GETFONTSMOOTHINGORIENTATION = 0x2012;
        public const uint SPI_GETFONTSMOOTHINGTYPE = 0x200a;
        public const uint SPI_GETFOREGROUNDFLASHCOUNT = 0x2004;
        public const uint SPI_GETFOREGROUNDLOCKTIMEOUT = 0x2000;
        public const uint SPI_GETGRADIENTCAPTIONS = 0x1008;
        public const uint SPI_GETGRIDGRANULARITY = 0x12;
        public const uint SPI_GETHIGHCONTRAST = 0x42;
        public const uint SPI_GETHOTTRACKING = 0x100e;
        public const uint SPI_GETICONMETRICS = 0x2d;
        public const uint SPI_GETICONTITLELOGFONT = 0x1f;
        public const uint SPI_GETICONTITLEWRAP = 0x19;
        public const uint SPI_GETKEYBOARDCUES = 0x100a;
        public const uint SPI_GETKEYBOARDDELAY = 0x16;
        public const uint SPI_GETKEYBOARDPREF = 0x44;
        public const uint SPI_GETKEYBOARDSPEED = 10;
        public const uint SPI_GETLISTBOXSMOOTHSCROLLING = 0x1006;
        public const uint SPI_GETLOWPOWERACTIVE = 0x53;
        public const uint SPI_GETLOWPOWERTIMEOUT = 0x4f;
        public const uint SPI_GETMENUANIMATION = 0x1002;
        public const uint SPI_GETMENUDROPALIGNMENT = 0x1b;
        public const uint SPI_GETMENUFADE = 0x1012;
        public const uint SPI_GETMENUSHOWDELAY = 0x6a;
        public const uint SPI_GETMENUUNDERLINES = 0x100a;
        public const uint SPI_GETMINIMIZEDMETRICS = 0x2b;
        public const uint SPI_GETMOUSE = 3;
        public const uint SPI_GETMOUSECLICKLOCK = 0x101e;
        public const uint SPI_GETMOUSECLICKLOCKTIME = 0x2008;
        public const uint SPI_GETMOUSEHOVERHEIGHT = 100;
        public const uint SPI_GETMOUSEHOVERTIME = 0x66;
        public const uint SPI_GETMOUSEHOVERWIDTH = 0x62;
        public const uint SPI_GETMOUSEKEYS = 0x36;
        public const uint SPI_GETMOUSESONAR = 0x101c;
        public const uint SPI_GETMOUSESPEED = 0x70;
        public const uint SPI_GETMOUSETRAILS = 0x5e;
        public const uint SPI_GETMOUSEVANISH = 0x1020;
        public const uint SPI_GETNONCLIENTMETRICS = 0x29;
        public const uint SPI_GETPOWEROFFACTIVE = 0x54;
        public const uint SPI_GETPOWEROFFTIMEOUT = 80;
        public const uint SPI_GETSCREENREADER = 70;
        public const uint SPI_GETSCREENSAVEACTIVE = 0x10;
        public const uint SPI_GETSCREENSAVERRUNNING = 0x72;
        public const uint SPI_GETSCREENSAVETIMEOUT = 14;
        public const uint SPI_GETSELECTIONFADE = 0x1014;
        public const uint SPI_GETSERIALKEYS = 0x3e;
        public const uint SPI_GETSHOWIMEUI = 110;
        public const uint SPI_GETSHOWSOUNDS = 0x38;
        public const uint SPI_GETSNAPTODEFBUTTON = 0x5f;
        public const uint SPI_GETSOUNDSENTRY = 0x40;
        public const uint SPI_GETSTICKYKEYS = 0x3a;
        public const uint SPI_GETTOGGLEKEYS = 0x34;
        public const uint SPI_GETTOOLTIPANIMATION = 0x1016;
        public const uint SPI_GETTOOLTIPFADE = 0x1018;
        public const uint SPI_GETUIEFFECTS = 0x103e;
        public const uint SPI_GETWHEELSCROLLLINES = 0x68;
        public const uint SPI_GETWINDOWSEXTENSION = 0x5c;
        public const uint SPI_GETWORKAREA = 0x30;
        public const uint SPI_ICONHORIZONTALSPACING = 13;
        public const uint SPI_ICONVERTICALSPACING = 0x18;
        public const uint SPI_LANGDRIVER = 12;
        public const uint SPI_SCREENSAVERRUNNING = 0x61;
        public const uint SPI_SETACCESSTIMEOUT = 0x3d;
        public const uint SPI_SETACTIVEWINDOWTRACKING = 0x1001;
        public const uint SPI_SETACTIVEWNDTRKTIMEOUT = 0x2003;
        public const uint SPI_SETACTIVEWNDTRKZORDER = 0x100d;
        public const uint SPI_SETANIMATION = 0x49;
        public const uint SPI_SETBEEP = 2;
        public const uint SPI_SETBLOCKSENDINPUTRESETS = 0x1027;
        public const uint SPI_SETBORDER = 6;
        public const uint SPI_SETCARETWIDTH = 0x2007;
        public const uint SPI_SETCOMBOBOXANIMATION = 0x1005;
        public const uint SPI_SETCURSORS = 0x57;
        public const uint SPI_SETCURSORSHADOW = 0x101b;
        public const uint SPI_SETDEFAULTINPUTLANG = 90;
        public const uint SPI_SETDESKPATTERN = 0x15;
        public const uint SPI_SETDESKWALLPAPER = 20;
        public const uint SPI_SETDOUBLECLICKTIME = 0x20;
        public const uint SPI_SETDOUBLECLKHEIGHT = 30;
        public const uint SPI_SETDOUBLECLKWIDTH = 0x1d;
        public const uint SPI_SETDRAGFULLWINDOWS = 0x25;
        public const uint SPI_SETDRAGHEIGHT = 0x4d;
        public const uint SPI_SETDRAGWIDTH = 0x4c;
        public const uint SPI_SETDROPSHADOW = 0x1025;
        public const uint SPI_SETFASTTASKSWITCH = 0x24;
        public const uint SPI_SETFILTERKEYS = 0x33;
        public const uint SPI_SETFLATMENU = 0x1023;
        public const uint SPI_SETFOCUSBORDERHEIGHT = 0x2011;
        public const uint SPI_SETFOCUSBORDERWIDTH = 0x200f;
        public const uint SPI_SETFONTSMOOTHING = 0x4b;
        public const uint SPI_SETFONTSMOOTHINGCONTRAST = 0x200d;
        public const uint SPI_SETFONTSMOOTHINGORIENTATION = 0x2013;
        public const uint SPI_SETFONTSMOOTHINGTYPE = 0x200b;
        public const uint SPI_SETFOREGROUNDFLASHCOUNT = 0x2005;
        public const uint SPI_SETFOREGROUNDLOCKTIMEOUT = 0x2001;
        public const uint SPI_SETGRADIENTCAPTIONS = 0x1009;
        public const uint SPI_SETGRIDGRANULARITY = 0x13;
        public const uint SPI_SETHANDHELD = 0x4e;
        public const uint SPI_SETHIGHCONTRAST = 0x43;
        public const uint SPI_SETHOTTRACKING = 0x100f;
        public const uint SPI_SETICONMETRICS = 0x2e;
        public const uint SPI_SETICONS = 0x58;
        public const uint SPI_SETICONTITLELOGFONT = 0x22;
        public const uint SPI_SETICONTITLEWRAP = 0x1a;
        public const uint SPI_SETKEYBOARDCUES = 0x100b;
        public const uint SPI_SETKEYBOARDDELAY = 0x17;
        public const uint SPI_SETKEYBOARDPREF = 0x45;
        public const uint SPI_SETKEYBOARDSPEED = 11;
        public const uint SPI_SETLANGTOGGLE = 0x5b;
        public const uint SPI_SETLISTBOXSMOOTHSCROLLING = 0x1007;
        public const uint SPI_SETLOWPOWERACTIVE = 0x55;
        public const uint SPI_SETLOWPOWERTIMEOUT = 0x51;
        public const uint SPI_SETMENUANIMATION = 0x1003;
        public const uint SPI_SETMENUDROPALIGNMENT = 0x1c;
        public const uint SPI_SETMENUFADE = 0x1013;
        public const uint SPI_SETMENUSHOWDELAY = 0x6b;
        public const uint SPI_SETMENUUNDERLINES = 0x100b;
        public const uint SPI_SETMINIMIZEDMETRICS = 0x2c;
        public const uint SPI_SETMOUSE = 4;
        public const uint SPI_SETMOUSEBUTTONSWAP = 0x21;
        public const uint SPI_SETMOUSECLICKLOCK = 0x101f;
        public const uint SPI_SETMOUSECLICKLOCKTIME = 0x2009;
        public const uint SPI_SETMOUSEHOVERHEIGHT = 0x65;
        public const uint SPI_SETMOUSEHOVERTIME = 0x67;
        public const uint SPI_SETMOUSEHOVERWIDTH = 0x63;
        public const uint SPI_SETMOUSEKEYS = 0x37;
        public const uint SPI_SETMOUSESONAR = 0x101d;
        public const uint SPI_SETMOUSESPEED = 0x71;
        public const uint SPI_SETMOUSETRAILS = 0x5d;
        public const uint SPI_SETMOUSEVANISH = 0x1021;
        public const uint SPI_SETNONCLIENTMETRICS = 0x2a;
        public const uint SPI_SETPENWINDOWS = 0x31;
        public const uint SPI_SETPOWEROFFACTIVE = 0x56;
        public const uint SPI_SETPOWEROFFTIMEOUT = 0x52;
        public const uint SPI_SETSCREENREADER = 0x47;
        public const uint SPI_SETSCREENSAVEACTIVE = 0x11;
        public const uint SPI_SETSCREENSAVERRUNNING = 0x61;
        public const uint SPI_SETSCREENSAVETIMEOUT = 15;
        public const uint SPI_SETSELECTIONFADE = 0x1015;
        public const uint SPI_SETSERIALKEYS = 0x3f;
        public const uint SPI_SETSHOWIMEUI = 0x6f;
        public const uint SPI_SETSHOWSOUNDS = 0x39;
        public const uint SPI_SETSNAPTODEFBUTTON = 0x60;
        public const uint SPI_SETSOUNDSENTRY = 0x41;
        public const uint SPI_SETSTICKYKEYS = 0x3b;
        public const uint SPI_SETTOGGLEKEYS = 0x35;
        public const uint SPI_SETTOOLTIPANIMATION = 0x1017;
        public const uint SPI_SETTOOLTIPFADE = 0x1019;
        public const uint SPI_SETUIEFFECTS = 0x103f;
        public const uint SPI_SETWHEELSCROLLLINES = 0x69;
        public const uint SPI_SETWORKAREA = 0x2f;
        public const uint SPIF_SENDCHANGE = 2;
        public const uint SPIF_SENDWININICHANGE = 2;
        public const uint SPIF_UPDATEINIFILE = 1;
        public const uint STATE_SYSTEM_ALERT_HIGH = 0x10000000;
        public const uint STATE_SYSTEM_ALERT_LOW = 0x4000000;
        public const uint STATE_SYSTEM_ALERT_MEDIUM = 0x8000000;
        public const uint STATE_SYSTEM_ANIMATED = 0x4000;
        public const uint STATE_SYSTEM_BUSY = 0x800;
        public const uint STATE_SYSTEM_CHECKED = 0x10;
        public const uint STATE_SYSTEM_COLLAPSED = 0x400;
        public const uint STATE_SYSTEM_DEFAULT = 0x100;
        public const uint STATE_SYSTEM_EXPANDED = 0x200;
        public const uint STATE_SYSTEM_EXTSELECTABLE = 0x2000000;
        public const uint STATE_SYSTEM_FLOATING = 0x1000;
        public const uint STATE_SYSTEM_FOCUSABLE = 0x100000;
        public const uint STATE_SYSTEM_FOCUSED = 4;
        public const uint STATE_SYSTEM_HOTTRACKED = 0x80;
        public const uint STATE_SYSTEM_INDETERMINATE = 0x20;
        public const uint STATE_SYSTEM_INVISIBLE = 0x8000;
        public const uint STATE_SYSTEM_LINKED = 0x400000;
        public const uint STATE_SYSTEM_MARQUEED = 0x2000;
        public const uint STATE_SYSTEM_MIXED = 0x20;
        public const uint STATE_SYSTEM_MOVEABLE = 0x40000;
        public const uint STATE_SYSTEM_MULTISELECTABLE = 0x1000000;
        public const uint STATE_SYSTEM_OFFSCREEN = 0x10000;
        public const uint STATE_SYSTEM_PRESSED = 8;
        public const uint STATE_SYSTEM_PROTECTED = 0x20000000;
        public const uint STATE_SYSTEM_READONLY = 0x40;
        public const uint STATE_SYSTEM_SELECTABLE = 0x200000;
        public const uint STATE_SYSTEM_SELECTED = 2;
        public const uint STATE_SYSTEM_SELFVOICING = 0x80000;
        public const uint STATE_SYSTEM_SIZEABLE = 0x20000;
        public const uint STATE_SYSTEM_TRAVERSED = 0x800000;
        public const uint STATE_SYSTEM_UNAVAILABLE = 1;
        public const uint STATE_SYSTEM_VALID = 0x3fffffff;
        public const short SW_FORCEMINIMIZE = 11;
        public const short SW_HIDE = 0;
        public const short SW_MAX = 11;
        public const short SW_MAXIMIZE = 3;
        public const short SW_MINIMIZE = 6;
        public const short SW_NORMAL = 1;
        public const short SW_RESTORE = 9;
        public const short SW_SHOW = 5;
        public const short SW_SHOWDEFAULT = 10;
        public const short SW_SHOWMAXIMIZED = 3;
        public const short SW_SHOWMINIMIZED = 2;
        public const short SW_SHOWMINNOACTIVE = 7;
        public const short SW_SHOWNA = 8;
        public const short SW_SHOWNOACTIVATE = 4;
        public const short SW_SHOWNORMAL = 1;
        public const uint SWP_ASYNCWINDOWPOS = 0x4000;
        public const uint SWP_DEFERERASE = 0x2000;
        public const uint SWP_DRAWFRAME = 0x20;
        public const uint SWP_FRAMECHANGED = 0x20;
        public const uint SWP_HIDEWINDOW = 0x80;
        public const uint SWP_NOACTIVATE = 0x10;
        public const uint SWP_NOCOPYBITS = 0x100;
        public const uint SWP_NOMOVE = 2;
        public const uint SWP_NOOWNERZORDER = 0x200;
        public const uint SWP_NOREDRAW = 8;
        public const uint SWP_NOREPOSITION = 0x200;
        public const uint SWP_NOSENDCHANGING = 0x400;
        public const uint SWP_NOSIZE = 1;
        public const uint SWP_NOZORDER = 4;
        public const uint SWP_SHOWWINDOW = 0x40;
        public const uint TME_CANCEL = 0x80000000;
        public const uint TME_HOVER = 1;
        public const uint TME_LEAVE = 2;
        public const uint TME_NONCLIENT = 0x10;
        public const uint TME_QUERY = 0x40000000;
        public const uint ULW_ALPHA = 2;
        public const uint ULW_COLORKEY = 1;
        public const uint ULW_OPAQUE = 4;
        public const uint UNICODE_NOCHAR = 0xffff;
        public const byte VK_0 = 0x30;
        public const byte VK_1 = 0x31;
        public const byte VK_2 = 50;
        public const byte VK_3 = 0x33;
        public const byte VK_4 = 0x34;
        public const byte VK_5 = 0x35;
        public const byte VK_6 = 0x36;
        public const byte VK_7 = 0x37;
        public const byte VK_8 = 0x38;
        public const byte VK_9 = 0x39;
        public const byte VK_A = 0x41;
        public const byte VK_ADD = 0x6b;
        public const byte VK_APPS = 0x5d;
        public const byte VK_ATTN = 0xf6;
        public const byte VK_B = 0x42;
        public const byte VK_BACK = 8;
        public const byte VK_C = 0x43;
        public const byte VK_CANCEL = 3;
        public const byte VK_CAPITAL = 20;
        public const byte VK_CLEAR = 12;
        public const byte VK_CONTROL = 0x11;
        public const byte VK_CRSEL = 0xf7;
        public const byte VK_D = 0x44;
        public const byte VK_DECIMAL = 110;
        public const byte VK_DIVIDE = 0x6f;
        public const byte VK_DOWN = 40;
        public const byte VK_E = 0x45;
        public const byte VK_END = 0x23;
        public const byte VK_EREOF = 0xf9;
        public const byte VK_ESCAPE = 0x1b;
        public const byte VK_EXECUTE = 0x2b;
        public const byte VK_EXSEL = 0xf8;
        public const byte VK_F = 70;
        public const byte VK_G = 0x47;
        public const byte VK_H = 0x48;
        public const byte VK_HELP = 0x2f;
        public const byte VK_HOME = 0x24;
        public const byte VK_I = 0x49;
        public const byte VK_J = 0x4a;
        public const byte VK_K = 0x4b;
        public const byte VK_L = 0x4c;
        public const byte VK_LBUTTON = 1;
        public const byte VK_LCONTROL = 0xa2;
        public const byte VK_LEFT = 0x25;
        public const byte VK_LMENU = 0xa4;
        public const byte VK_LSHIFT = 160;
        public const byte VK_LWIN = 0x5b;
        public const byte VK_M = 0x4d;
        public const byte VK_MENU = 0x12;
        public const byte VK_MULTIPLY = 0x6a;
        public const byte VK_N = 0x4e;
        public const byte VK_NEXT = 0x22;
        public const byte VK_NONAME = 0xfc;
        public const byte VK_NUMPAD0 = 0x60;
        public const byte VK_NUMPAD1 = 0x61;
        public const byte VK_NUMPAD2 = 0x62;
        public const byte VK_NUMPAD3 = 0x63;
        public const byte VK_NUMPAD4 = 100;
        public const byte VK_NUMPAD5 = 0x65;
        public const byte VK_NUMPAD6 = 0x66;
        public const byte VK_NUMPAD7 = 0x67;
        public const byte VK_NUMPAD8 = 0x68;
        public const byte VK_NUMPAD9 = 0x69;
        public const byte VK_O = 0x4f;
        public const byte VK_OEM_CLEAR = 0xfe;
        public const byte VK_P = 80;
        public const byte VK_PA1 = 0xfd;
        public const byte VK_PLAY = 250;
        public const byte VK_PRIOR = 0x21;
        public const byte VK_Q = 0x51;
        public const byte VK_R = 0x52;
        public const byte VK_RCONTROL = 0xa3;
        public const byte VK_RETURN = 13;
        public const byte VK_RIGHT = 0x27;
        public const byte VK_RMENU = 0xa5;
        public const byte VK_RSHIFT = 0xa1;
        public const byte VK_RWIN = 0x5c;
        public const byte VK_S = 0x53;
        public const byte VK_SELECT = 0x29;
        public const byte VK_SEPARATOR = 0x6c;
        public const byte VK_SHIFT = 0x10;
        public const byte VK_SNAPSHOT = 0x2c;
        public const byte VK_SPACE = 0x20;
        public const byte VK_SUBTRACT = 0x6d;
        public const byte VK_T = 0x54;
        public const byte VK_TAB = 9;
        public const byte VK_U = 0x55;
        public const byte VK_UP = 0x26;
        public const byte VK_V = 0x56;
        public const byte VK_W = 0x57;
        public const byte VK_X = 0x58;
        public const byte VK_Y = 0x59;
        public const byte VK_Z = 90;
        public const byte VK_ZOOM = 0xfb;
        public const uint WA_ACTIVE = 1;
        public const uint WA_CLICKACTIVE = 2;
        public const uint WA_INACTIVE = 0;
        public const int WH_CALLWNDPROC = 4;
        public const int WH_CALLWNDPROCRET = 12;
        public const int WH_CBT = 5;
        public const int WH_DEBUG = 9;
        public const int WH_FOREGROUNDIDLE = 11;
        public const int WH_GETMESSAGE = 3;
        public const int WH_HARDWARE = 8;
        public const int WH_JOURNALPLAYBACK = 1;
        public const int WH_JOURNALRECORD = 0;
        public const int WH_KEYBOARD = 2;
        public const int WH_KEYBOARD_LL = 13;
        public const int WH_MAX = 14;
        public const int WH_MAXHOOK = 14;
        public const int WH_MIN = -1;
        public const int WH_MINHOOK = -1;
        public const int WH_MOUSE = 7;
        public const int WH_MOUSE_LL = 14;
        public const int WH_MSGFILTER = -1;
        public const int WH_SHELL = 10;
        public const int WH_SYSMSGFILTER = 6;
        public const uint WM_ACTIVATE = 6;
        public const uint WM_ACTIVATEAPP = 0x1c;
        public const uint WM_CANCELJOURNAL = 0x4b;
        public const uint WM_CANCELMODE = 0x1f;
        public const uint WM_CAPTURECHANGED = 0x215;
        public const uint WM_CHANGEUISTATE = 0x127;
        public const uint WM_CHAR = 0x102;
        public const uint WM_CHARTOITEM = 0x2f;
        public const uint WM_CHILDACTIVATE = 0x22;
        public const uint WM_CLOSE = 0x10;
        public const uint WM_COMMAND = 0x111;
        public const uint WM_COMMNOTIFY = 0x44;
        public const uint WM_COMPACTING = 0x41;
        public const uint WM_COMPAREITEM = 0x39;
        public const uint WM_COPYDATA = 0x4a;
        public const uint WM_CREATE = 1;
        public const uint WM_CTLCOLORBTN = 0x135;
        public const uint WM_CTLCOLORDLG = 310;
        public const uint WM_CTLCOLOREDIT = 0x133;
        public const uint WM_CTLCOLORLISTBOX = 0x134;
        public const uint WM_CTLCOLORMSGBOX = 0x132;
        public const uint WM_CTLCOLORSCROLLBAR = 0x137;
        public const uint WM_CTLCOLORSTATIC = 0x138;
        public const uint WM_DEADCHAR = 0x103;
        public const uint WM_DELETEITEM = 0x2d;
        public const uint WM_DESTROY = 2;
        public const uint WM_DEVMODECHANGE = 0x1b;
        public const uint WM_DRAWITEM = 0x2b;
        public const uint WM_DROPFILES = 0x233;
        public const uint WM_ENABLE = 10;
        public const uint WM_ENDSESSION = 0x16;
        public const uint WM_ENTERIDLE = 0x121;
        public const uint WM_ENTERMENULOOP = 0x211;
        public const uint WM_ENTERSIZEMOVE = 0x231;
        public const uint WM_ERASEBKGND = 20;
        public const uint WM_EXITMENULOOP = 530;
        public const uint WM_EXITSIZEMOVE = 0x232;
        public const uint WM_FONTCHANGE = 0x1d;
        public const uint WM_GETDLGCODE = 0x87;
        public const uint WM_GETFONT = 0x31;
        public const uint WM_GETHOTKEY = 0x33;
        public const uint WM_GETMINMAXINFO = 0x24;
        public const uint WM_GETOBJECT = 0x3d;
        public const uint WM_GETTEXT = 13;
        public const uint WM_GETTEXTLENGTH = 14;
        public const uint WM_HSCROLL = 0x114;
        public const uint WM_ICONERASEBKGND = 0x27;
        public const uint WM_IME_COMPOSITION = 0x10f;
        public const uint WM_IME_ENDCOMPOSITION = 270;
        public const uint WM_IME_KEYLAST = 0x10f;
        public const uint WM_IME_STARTCOMPOSITION = 0x10d;
        public const uint WM_INITDIALOG = 0x110;
        public const uint WM_INITMENU = 0x116;
        public const uint WM_INITMENUPOPUP = 0x117;
        public const uint WM_INPUT = 0xff;
        public const uint WM_KEYDOWN = 0x100;
        public const uint WM_KEYFIRST = 0x100;
        public const uint WM_KEYLAST = 0x109;
        public const uint WM_KEYUP = 0x101;
        public const uint WM_KILLFOCUS = 8;
        public const uint WM_LBUTTONDBLCLK = 0x203;
        public const uint WM_LBUTTONDOWN = 0x201;
        public const uint WM_LBUTTONUP = 0x202;
        public const uint WM_MBUTTONDBLCLK = 0x209;
        public const uint WM_MBUTTONDOWN = 0x207;
        public const uint WM_MBUTTONUP = 520;
        public const uint WM_MDIACTIVATE = 0x222;
        public const uint WM_MDICASCADE = 0x227;
        public const uint WM_MDICREATE = 0x220;
        public const uint WM_MDIDESTROY = 0x221;
        public const uint WM_MDIGETACTIVE = 0x229;
        public const uint WM_MDIICONARRANGE = 0x228;
        public const uint WM_MDIMAXIMIZE = 0x225;
        public const uint WM_MDINEXT = 0x224;
        public const uint WM_MDIREFRESHMENU = 0x234;
        public const uint WM_MDIRESTORE = 0x223;
        public const uint WM_MDISETMENU = 560;
        public const uint WM_MDITILE = 550;
        public const uint WM_MEASUREITEM = 0x2c;
        public const uint WM_MENUCHAR = 0x120;
        public const uint WM_MENUCOMMAND = 0x126;
        public const uint WM_MENUDRAG = 0x123;
        public const uint WM_MENUGETOBJECT = 0x124;
        public const uint WM_MENURBUTTONUP = 290;
        public const uint WM_MENUSELECT = 0x11f;
        public const uint WM_MOUSEACTIVATE = 0x21;
        public const uint WM_MOUSEFIRST = 0x200;
        public const uint WM_MOUSELAST = 0x20d;
        public const uint WM_MOUSELEAVE = 0x2a3;
        public const uint WM_MOUSEMOVE = 0x200;
        public const uint WM_MOUSEWHEEL = 0x20a;
        public const uint WM_MOVE = 3;
        public const uint WM_MOVING = 0x216;
        public const uint WM_NCACTIVATE = 0x86;
        public const uint WM_NCCALCSIZE = 0x83;
        public const uint WM_NCCREATE = 0x81;
        public const uint WM_NCDESTROY = 130;
        public const uint WM_NCHITTEST = 0x84;
        public const uint WM_NCLBUTTONDBLCLK = 0xa3;
        public const uint WM_NCLBUTTONDOWN = 0xa1;
        public const uint WM_NCLBUTTONUP = 0xa2;
        public const uint WM_NCMBUTTONDBLCLK = 0xa9;
        public const uint WM_NCMBUTTONDOWN = 0xa7;
        public const uint WM_NCMBUTTONUP = 0xa8;
        public const uint WM_NCMOUSELEAVE = 0x2a2;
        public const uint WM_NCMOUSEMOVE = 160;
        public const uint WM_NCPAINT = 0x85;
        public const uint WM_NCRBUTTONDBLCLK = 0xa6;
        public const uint WM_NCRBUTTONDOWN = 0xa4;
        public const uint WM_NCRBUTTONUP = 0xa5;
        public const uint WM_NCXBUTTONDBLCLK = 0xad;
        public const uint WM_NCXBUTTONDOWN = 0xab;
        public const uint WM_NCXBUTTONUP = 0xac;
        public const uint WM_NEXTDLGCTL = 40;
        public const uint WM_NEXTMENU = 0x213;
        public const uint WM_NULL = 0;
        public const uint WM_PAINT = 15;
        public const uint WM_PAINTICON = 0x26;
        public const uint WM_PARENTNOTIFY = 0x210;
        public const uint WM_POWER = 0x48;
        public const uint WM_QUERYDRAGICON = 0x37;
        public const uint WM_QUERYENDSESSION = 0x11;
        public const uint WM_QUERYOPEN = 0x13;
        public const uint WM_QUERYUISTATE = 0x129;
        public const uint WM_QUEUESYNC = 0x23;
        public const uint WM_QUIT = 0x12;
        public const uint WM_RBUTTONDBLCLK = 0x206;
        public const uint WM_RBUTTONDOWN = 0x204;
        public const uint WM_RBUTTONUP = 0x205;
        public const uint WM_SETCURSOR = 0x20;
        public const uint WM_SETFOCUS = 7;
        public const uint WM_SETFONT = 0x30;
        public const uint WM_SETHOTKEY = 50;
        public const uint WM_SETREDRAW = 11;
        public const uint WM_SETTEXT = 12;
        public const uint WM_SETTINGCHANGE = 0x1a;
        public const uint WM_SHOWWINDOW = 0x18;
        public const uint WM_SIZE = 5;
        public const uint WM_SIZING = 0x214;
        public const uint WM_SPOOLERSTATUS = 0x2a;
        public const int WM_STARTRESTOREPROC = 0x20d2;
        public const uint WM_SYNCPAINT = 0x88;
        public const uint WM_SYSCHAR = 0x106;
        public const uint WM_SYSCOLORCHANGE = 0x15;
        public const uint WM_SYSCOMMAND = 0x112;
        public const uint WM_SYSDEADCHAR = 0x107;
        public const uint WM_SYSKEYDOWN = 260;
        public const uint WM_SYSKEYUP = 0x105;
        public const uint WM_TIMECHANGE = 30;
        public const uint WM_TIMER = 0x113;
        public const uint WM_UNICHAR = 0x109;
        public const uint WM_UNINITMENUPOPUP = 0x125;
        public const uint WM_UPDATEUISTATE = 0x128;
        public const uint WM_USER = 0x400;
        public const int WM_USERPROCALIVE = 0x20d1;
        public const int WM_USERRESETMAINMENU = 0x20d3;
        public const uint WM_VKEYTOITEM = 0x2e;
        public const uint WM_VSCROLL = 0x115;
        public const uint WM_WINDOWPOSCHANGED = 0x47;
        public const uint WM_WINDOWPOSCHANGING = 70;
        public const uint WM_WININICHANGE = 0x1a;
        public const uint WM_XBUTTONDBLCLK = 0x20d;
        public const uint WM_XBUTTONDOWN = 0x20b;
        public const uint WM_XBUTTONUP = 0x20c;
        public const uint WS_BORDER = 0x800000;
        public const uint WS_CAPTION = 0xc00000;
        public const uint WS_CHILD = 0x40000000;
        public const uint WS_CLIPCHILDREN = 0x2000000;
        public const uint WS_CLIPSIBLINGS = 0x4000000;
        public const uint WS_DISABLED = 0x8000000;
        public const uint WS_DLGFRAME = 0x400000;
        public const uint WS_EX_ACCEPTFILES = 0x10;
        public const uint WS_EX_APPWINDOW = 0x40000;
        public const uint WS_EX_CLIENTEDGE = 0x200;
        public const uint WS_EX_CONTEXTHELP = 0x400;
        public const uint WS_EX_CONTROLPARENT = 0x10000;
        public const uint WS_EX_DLGMODALFRAME = 1;
        public const uint WS_EX_LAYERED = 0x80000;
        public const uint WS_EX_LAYOUTRTL = 0x400000;
        public const uint WS_EX_LEFT = 0;
        public const uint WS_EX_LEFTSCROLLBAR = 0x4000;
        public const uint WS_EX_LTRREADING = 0;
        public const uint WS_EX_MDICHILD = 0x40;
        public const uint WS_EX_NOINHERITLAYOUT = 0x100000;
        public const uint WS_EX_NOPARENTNOTIFY = 4;
        public const uint WS_EX_OVERLAPPEDWINDOW = 0x300;
        public const uint WS_EX_PALETTEWINDOW = 0x188;
        public const uint WS_EX_RIGHT = 0x1000;
        public const uint WS_EX_RIGHTSCROLLBAR = 0;
        public const uint WS_EX_RTLREADING = 0x2000;
        public const uint WS_EX_STATICEDGE = 0x20000;
        public const uint WS_EX_TOOLWINDOW = 0x80;
        public const uint WS_EX_TOPMOST = 8;
        public const uint WS_EX_TRANSPARENT = 0x20;
        public const uint WS_EX_WINDOWEDGE = 0x100;
        public const uint WS_GROUP = 0x20000;
        public const uint WS_HSCROLL = 0x100000;
        public const uint WS_MAXIMIZE = 0x1000000;
        public const uint WS_MAXIMIZEBOX = 0x10000;
        public const uint WS_MINIMIZE = 0x20000000;
        public const uint WS_MINIMIZEBOX = 0x20000;
        public const uint WS_OVERLAPPED = 0;
        public const uint WS_POPUP = 0x80000000;
        public const uint WS_SYSMENU = 0x80000;
        public const uint WS_TABSTOP = 0x10000;
        public const uint WS_THICKFRAME = 0x40000;
        public const uint WS_VISIBLE = 0x10000000;
        public const uint WS_VSCROLL = 0x200000;
        public const uint WVR_ALIGNBOTTOM = 0x40;
        public const uint WVR_ALIGNLEFT = 0x20;
        public const uint WVR_ALIGNRIGHT = 0x80;
        public const uint WVR_ALIGNTOP = 0x10;
        public const uint WVR_HREDRAW = 0x100;
        public const uint WVR_REDRAW = 0x300;
        public const uint WVR_VALIDRECTS = 0x400;
        public const uint WVR_VREDRAW = 0x200;

        [StructLayout(LayoutKind.Sequential)]
        public struct CBT_CREATEWND
        {
            public IntPtr lpcs;
            public IntPtr hwndInsertAfter;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct COMBOBOXINFO
        {
            public uint cbSize;
            public xae4dd1cafd2eb77c.RECT rcItem;
            public xae4dd1cafd2eb77c.RECT rcButton;
            public uint stateButton;
            public IntPtr hwndCombo;
            public IntPtr hwndItem;
            public IntPtr hwndList;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct CREATESTRUCT
        {
            public IntPtr lpCreateParams;
            public IntPtr hInstance;
            public IntPtr hMenu;
            public IntPtr hwndParent;
            public int cy;
            public int cx;
            public int y;
            public int x;
            public long style;
            public IntPtr lpszName;
            public IntPtr lpszClass;
            public uint dwExStyle;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct LOGFONT
        {
            public int lfHeight;
            public int lfWidth;
            public int lfEscapement;
            public int lfOrientation;
            public int lfWeight;
            public byte lfItalic;
            public byte lfUnderline;
            public byte lfStrikeOut;
            public byte lfCharSet;
            public byte lfOutPrecision;
            public byte lfClipPrecision;
            public byte lfQuality;
            public byte lfPitchAndFamily;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst=0x20)]
            public byte[] lfFaceName;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct MSG
        {
            public IntPtr hwnd;
            public uint message;
            public IntPtr wParam;
            public IntPtr lParam;
            public int time;
            public int pt_x;
            public int pt_y;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct NCCALCSIZE_PARAMS
        {
            public Rectangle rgrc0;
            public Rectangle rgrc1;
            public Rectangle rgrc2;
            public IntPtr lppos;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct NONCLIENTMETRICS
        {
            public uint cbSize;
            public int iBorderWidth;
            public int iScrollWidth;
            public int iScrollHeight;
            public int iCaptionWidth;
            public int iCaptionHeight;
            public int iSmCaptionWidth;
            public int iSmCaptionHeight;
            [MarshalAs(UnmanagedType.Struct)]
            public x40255b11ef821fa3.LOGFONT lfCaptionFont;
            public int iMenuWidth;
            public int iMenuHeight;
            [MarshalAs(UnmanagedType.Struct)]
            public x40255b11ef821fa3.LOGFONT lfSmCaptionFont;
            [MarshalAs(UnmanagedType.Struct)]
            public x40255b11ef821fa3.LOGFONT lfMenuFont;
            [MarshalAs(UnmanagedType.Struct)]
            public x40255b11ef821fa3.LOGFONT lfStatusFont;
            [MarshalAs(UnmanagedType.Struct)]
            public x40255b11ef821fa3.LOGFONT lfMessageFont;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct PAINTSTRUCT
        {
            public IntPtr hdc;
            public int fErase;
            public Rectangle rcPaint;
            public int fRestore;
            public int fIncUpdate;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst=0x20)]
            public byte[] rgbReserved;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct SCROLLBARINFO
        {
            public uint cbSize;
            public xae4dd1cafd2eb77c.RECT rcScrollBar;
            public int dxyLineButton;
            public int xyThumbTop;
            public int xyThumbBottom;
            public int reserved;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst=0x18)]
            public uint[] rgstate;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct SCROLLINFO
        {
            public uint cbSize;
            public uint fMask;
            public int nMin;
            public int nMax;
            public uint nPage;
            public int nPos;
            public int nTrackPos;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct STYLESTRUCT
        {
            public uint styleOld;
            public uint styleNew;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct TITLEBARINFO
        {
            public uint cbSize;
            public xae4dd1cafd2eb77c.RECT rcTitleBar;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst=6)]
            public uint[] rgstate;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct TRACKMOUSEEVENTS
        {
            public uint cbSize;
            public uint dwFlags;
            public IntPtr hWnd;
            public uint dwHoverTime;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct WINDOWINFO
        {
            public uint cbSize;
            public Rectangle rcWindow;
            public Rectangle rcClient;
            public uint dwStyle;
            public uint dwExStyle;
            public uint dwWindowStatus;
            public uint cxWindowBorders;
            public uint cyWindowBorders;
            private short xd5bc19ea3b69957a;
            private short x4fef15cc26e7f565;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct WINDOWPLACEMENT
        {
            public uint length;
            public uint flags;
            public uint showCmd;
            public Point ptMinPosition;
            public Point ptMaxPosition;
            public Rectangle rcNormalPosition;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct WINDOWPOS
        {
            public IntPtr hwnd;
            public IntPtr hwndInsertAfter;
            public int x;
            public int y;
            public int cx;
            public int cy;
            public uint flags;
        }
    }
}

